import { FormEvent, useState } from 'react';
import { Navigate } from 'react-router-dom';
import { Route, Mail, Lock, UserRound, ArrowRight } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
export default function Auth(){
 const {user,login,signup}=useAuth(); const [mode,setMode]=useState<'login'|'signup'>('login'); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 if(user) return <Navigate to="/" replace/>;
 async function submit(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{if(mode==='signup') await signup(name,email,password); else await login(email,password);}catch(err:any){setError(err?.message?.replace('Firebase: ','')||'Authentication failed.')}finally{setBusy(false)}}
 return <div className="auth-page"><div className="auth-brand"><div className="brand-mark"><Route size={24}/></div><div><div className="brand-name">Lakbay</div><div className="brand-sub">Smart Trip Planner</div></div></div><div className="auth-card"><span className="section-kicker">{mode==='login'?'Welcome back':'Create account'}</span><h1>{mode==='login'?'Continue your journey':'Start planning smarter trips'}</h1><p>{mode==='login'?'Sign in to access your vehicles and saved trips.':'Your garage and trip history will sync securely with your account.'}</p><form onSubmit={submit} className="auth-form">{mode==='signup'&&<label><span>Name</span><div className="input-shell"><UserRound size={18}/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></div></label>}<label><span>Email</span><div className="input-shell"><Mail size={18}/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></div></label><label><span>Password</span><div className="input-shell"><Lock size={18}/><input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></div></label>{error&&<div className="form-error">{error}</div>}<button disabled={busy} className="primary-btn wide">{busy?'Please wait...':mode==='login'?'Sign in':'Create account'} <ArrowRight size={17}/></button></form><button className="auth-switch" onClick={()=>{setMode(mode==='login'?'signup':'login');setError('')}}>{mode==='login'?"Don't have an account? Create one":"Already have an account? Sign in"}</button></div></div>
}
